### ISSUE TITLE
Generated files out of sync

### ISSUE THREAD

**Issue by overlookmotel** [oxc-project/oxc-browserslist#61]
On local machine, if pull latest main, and then run:

```sh
rm -r node_modules
pnpm install
cargo codegen
```

then 3 x generated files (e.g. `src/generated/caniuse_browsers.rs`) show changes. i.e. committed versions of generated files are out of date.

Once they are updated with `cargo codegen`, `cargo test` then fails.

## Problems

It looks like there are 2 problems:

1. Committed generated files are out of date.
2. NPM package versions are out of sync:

* `caniuse-db` depended on by this crate = 1.0.30001640
* `caniuse-lite` depended on by `browserslist` = 1.0.30001639

In the 1.0.30001640 update, Opera 111 was added. This discrepancy causes a difference in output between `browserslist` and `oxc_browserslist`, which causes the test failures.

## Solutions

The first problem could be spotted by adding a task to CI which runs `cargo codegen` and fails if there's a difference between what's committed and what fresh run of `cargo codegen` generates - like Oxc's [`ast_changes` CI task](https://github.com/oxc-project/oxc/blob/b2ff2df5afd257367a98542a27071b62cfbb5242/.github/workflows/ci.yml#L273-L296)

I'm not sure how best to solve the dependency mismatch issue.

Could we add a dependency on `caniuse-lite` to `package.json`? Presumably that'd keep the 2 in sync as they'd get updated together - although I guess it's theoretically possible we might have the bad luck to update dependencies in the time between a `caniuse` update being released, and `browserslist` being updated to use it.

Or should we instead edit `pnpm-lock.yaml` to make `browserslist`'s dependency on `caniuse-lite` match the version of `caniuse-db` we're using?

@Boshen What's the best way to approach this?

**Comment by Boshen** [comment]
I was hoping that renovate bot can update the deps until CI passes so I can merge ... but it seems like everything is breaking apart https://github.com/oxc-project/oxc-browserslist/pull/57

**Comment by Boshen** [comment]
Added `git diff` check to break the main branch.

https://github.com/oxc-project/oxc-browserslist/actions/runs/10468325234/job/28988965933

**Comment by Boshen** [comment]
I don't know what's breaking even I try to `pnpm upgrade` everything to the latest 🤔

**Comment by Boshen** [comment]
let me try peer dependencies to keep them in sync ...

**Comment by Boshen** [comment]
All fixed.
